### ISSUE TITLE
DVIA-v2.app does not contain a valid Info.plist, so it cannot be installed on iPhone 5s.

### ISSUE THREAD

**Issue by mrbiggleswirth** [prateek147/DVIA-v2#11]
I have followed multiple DVIA install guides using different installation techniques, including the official ones. But I'm not able to compile the code on my Mac computer without a bunch of errors and warnings.
https://github.com/prateek147/DVIA-v2

I then tried to follow the tips from this recent guide from July 2020. Where he uses Xcode to install the .ipa file or extracted .ipa file. But I get this error.
https://philkeeble.com/ios/Setting-Up-iOS/

> Unable to install “DVIA-v2-swift“.
> 
> DVIA-v2.app does not contain a valid Info.plist, so it cannot be installed on iPhone 5s.
> 
> (“CFBundleExecutable“ specifies a file that is not executable)

How should I proceed to make Xcode happy with my downloaded DVIA-v2 source codes?

**Comment by prateek147** [comment]
Hi @mrbiggleswirth you can compile the app using the latest code. For the binary installation, you can use Apple Configurator app to install the application on your device
