### ISSUE TITLE
Several Security Vulerabilities

### ISSUE THREAD

**Issue by CodeLikeCrazE** [prateek147/DVIA-v2#12]
This app has several security vulnerabilities, even a Touch ID bypass. Please fix them. :)

**Comment by CodeLikeCrazE** [comment]
I feel like the misspelled title makes this even better.

**Comment by Tokarak** [comment]
I just hope there is nothing which an unautharised external attacker can use. Probably not, as a jailbreak is already more dangerous.

**Comment by prateek147** [comment]
This is a vulnerable app for learning purposes :D
