### ISSUE TITLE
unbound variable

### ISSUE THREAD

**Issue by ITmustang** [prateek147/DVIA-v2#15]
when compiling code, xcode errors out stating...

DVIA-v2/DVIA-v2/Pods/Target Support Files/Pods-DVIA-v2/Pods-DVIA-v2-frameworks.sh: line 132: ARCHS[@]: unbound variable
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by prateek147** [comment]
Fixed in the latest commit, thanks for reporting this.
