### ISSUE TITLE
Impactor installation issue 

### ISSUE THREAD

**Issue by alokc83** [prateek147/DVIA-v2#4]
```
installation.cpp:42
The WatchKit 2.0 app being installed contains an invalid application executable
```
Getting above error on a device that is on 10.3.3

**Comment by qrx** [comment]
I get the same on iOS 12.0

**Comment by aupsham** [comment]
I think i am too late to reply over this,
we can install this application by various methods mention in this article. 
https://book.hacktricks.xyz/mobile-apps-pentesting/ios-pentesting/basic-ios-testing-operations#installing-apps
The best way to install this is that add the AppSync repo in your cydia 
and then fallow any one method mentioned in the above article

**Comment by prateekcareem2** [comment]
Pleaase use Apple Configurator app.
