### ISSUE TITLE
Build Errors in Swift version

### ISSUE THREAD

**Issue by martialhax** [prateek147/DVIA-v2#5]
Hi Prateek,

Attemptoing to run Swift version in Simulator per instructions. I chnge a few settings to make Build go, but few errors left. Opening Workspace only and running pods install etc. etc. Run Command-R and almost completes but for few Swift compilation errors (attached screen).

Thank you for any guidance.

<img width="1151" alt="screen shot 2019-01-30 at 4 02 42 pm" src="https://user-images.githubusercontent.com/17996721/52015911-bddd1880-24a8-11e9-8f75-976d084c3128.png">

**Comment by tmaestrelli** [comment]
What worked for me:
Donwload the last XCode version (
Clone the DVIA repo , 
`git clone https://github.com/prateek147/DVIA-v2`
Install pod
`$ sudo gem install cocoapods
export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/bin:$PATH`
Swap to the application folder and do
`pod deintegrate
pod update
pod install`
After that, open DVIA-v2.xcworkspace

I've also set ios 11.2 inside Podfile just in case
`use_frameworks!

target 'DVIA-v2' do
    platform :ios, '11.2'
    pod 'Parse'
    pod 'GoogleAnalytics'
    pod 'RealmSwift'
    pod 'couchbase-lite-ios'
    pod 'Flurry-iOS-SDK/FlurrySDK'
end`

**Comment by martialhax** [comment]
Thanks tmaestrelli...I'll give it a go again over the weekend.

**Comment by hongsolo9** [comment]
@tmaestrelli Thanks for the heads up! I managed to get it running with your steps.

After executing the above steps, run the following to get a running iOS app.
1. Use Xcode to o pen DVIA-2.xcworkspace
2. From the General Tab, amend the bundle identifier (ie change com.HighAltitudeHacks.DVIAswiftv2 to com.h.d)
3. Still at the General Tab, change the deployment target to reflect the version of iOS running on the phone.
4. Xcode should be indexing the entire workspace. Once it stops,  go to File -> Workspace Settings and change the Build System to Legacy Build System.
5. [Command + Shift + k] to clear Xcode.
6. Then compile the program.
7. You should see one error which needs to be fixed before compiling will complete.
8. Amend the offending code as follows:
![Look-at-the-slashes](https://user-images.githubusercontent.com/1450374/63146197-b89e8000-c02c-11e9-89d5-634876bd1f08.png)
9. Compile the program again.
